<?php

use App\InvoiceDetails;
use Illuminate\Database\Seeder;

class InvoiceDetailsTableSeeder extends Seeder
{
    public function run() {
        InvoiceDetails::insert([
            [
                'invoice_id' => 1,
                'medicine_id' => 3,
                'medicine_name' => 'Rhinozol 15ml',
                'sell_price' => 25.00,
                'qty' => 4,
                'total_price' => 100.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 1,
                'medicine_id' => 1,
                'medicine_name' => 'Fenadin 180',
                'sell_price' => 10.00,
                'qty' => 22,
                'total_price' => 220.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 2,
                'medicine_id' => 11,
                'medicine_name' => 'Pol Plus BP 500mg',
                'sell_price' => 3.00,
                'qty' => 20,
                'total_price' => 60.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 2,
                'medicine_id' => 7,
                'medicine_name' => 'Napa 500',
                'sell_price' => 2.00,
                'qty' => 20,
                'total_price' => 40.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 3,
                'medicine_id' => 6,
                'medicine_name' => 'Doxicap 100',
                'sell_price' => 10.00,
                'qty' => 30,
                'total_price' => 300.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 3,
                'medicine_id' => 2,
                'medicine_name' => 'Duofix 500',
                'sell_price' => 15.00,
                'qty' => 10,
                'total_price' => 150.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 4,
                'medicine_id' => 10,
                'medicine_name' => 'Trevox 500',
                'sell_price' => 15.00,
                'qty' => 10,
                'total_price' => 150.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 4,
                'medicine_id' => 5,
                'medicine_name' => 'Zif-CI',
                'sell_price' => 12.00,
                'qty' => 10,
                'total_price' => 120.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 5,
                'medicine_id' => 7,
                'medicine_name' => 'Napa 500',
                'sell_price' => 2.00,
                'qty' => 20,
                'total_price' => 40.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 5,
                'medicine_id' => 4,
                'medicine_name' => 'Ranid 150mg',
                'sell_price' => 5.00,
                'qty' => 10,
                'total_price' => 50.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 6,
                'medicine_id' => 3,
                'medicine_name' => 'Rhinozol 15ml',
                'sell_price' => 25.00,
                'qty' => 5,
                'total_price' => 125.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 6,
                'medicine_id' => 10,
                'medicine_name' => 'Trevox 500',
                'sell_price' => 15.00,
                'qty' => 20,
                'total_price' => 300.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 7,
                'medicine_id' => 1,
                'medicine_name' => 'Fenadin 180',
                'sell_price' => 10.00,
                'qty' => 20,
                'total_price' => 200.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 7,
                'medicine_id' => 5,
                'medicine_name' => 'Zif-CI',
                'sell_price' => 12.00,
                'qty' => 30,
                'total_price' => 360.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 8,
                'medicine_id' => 2,
                'medicine_name' => 'Duofix 500',
                'sell_price' => 15.00,
                'qty' => 20,
                'total_price' => 300.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 8,
                'medicine_id' => 5,
                'medicine_name' => 'Zif-CI',
                'sell_price' => 12.00,
                'qty' => 10,
                'total_price' => 120.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 9,
                'medicine_id' => 4,
                'medicine_name' => 'Ranid 150mg',
                'sell_price' => 5.00,
                'qty' => 20,
                'total_price' => 100.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 9,
                'medicine_id' => 1,
                'medicine_name' => 'Fenadin 180',
                'sell_price' => 10.00,
                'qty' => 20,
                'total_price' => 200.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 9,
                'medicine_id' => 2,
                'medicine_name' => 'Duofix 500',
                'sell_price' => 15.00,
                'qty' => 15,
                'total_price' => 225.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 10,
                'medicine_id' => 7,
                'medicine_name' => 'Napa 500',
                'sell_price' => 2.00,
                'qty' => 30,
                'total_price' => 60.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 10,
                'medicine_id' => 5,
                'medicine_name' => 'Zif-CI',
                'sell_price' => 12.00,
                'qty' => 20,
                'total_price' => 240.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 10,
                'medicine_id' => 3,
                'medicine_name' => 'Rhinozol 15ml',
                'sell_price' => 25.00,
                'qty' => 4,
                'total_price' => 100.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 11,
                'medicine_id' => 7,
                'medicine_name' => 'Napa 500',
                'sell_price' => 2.00,
                'qty' => 20,
                'total_price' => 40.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 11,
                'medicine_id' => 6,
                'medicine_name' => 'Doxicap 100',
                'sell_price' => 10.00,
                'qty' => 20,
                'total_price' => 200.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 11,
                'medicine_id' => 2,
                'medicine_name' => 'Duofix 500',
                'sell_price' => 15.00,
                'qty' => 30,
                'total_price' => 450.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 12,
                'medicine_id' => 10,
                'medicine_name' => 'Trevox 500',
                'sell_price' => 15.00,
                'qty' => 20,
                'total_price' => 300.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 12,
                'medicine_id' => 5,
                'medicine_name' => 'Zif-CI',
                'sell_price' => 12.00,
                'qty' => 10,
                'total_price' => 120.00,
                'created_at' => now(),
            ],
            [
                'invoice_id' => 12,
                'medicine_id' => 1,
                'medicine_name' => 'Fenadin 180',
                'sell_price' => 10.00,
                'qty' => 20,
                'total_price' => 200.00,
                'created_at' => now(),
            ],
        ]);
    }
}
