<?php

use App\Invoice;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class InvoicesTableSeeder extends Seeder
{
    public function run() {
        Invoice::insert([
            [ 
                'branch_id' => 1,
                'user_id' => 5,
                'customer_id' => 1,
                'invoice_date' => Carbon::parse(now())->format('Y-m-d'),
                'payment_type' => 'Cash',
                'invoice_total' => 320.00,
                'invoice_discount' => 20.00,
                'invoice_nettotal' => 300.00,
                'invoice_received' => 300.00,
                'invoice_due' => 0.00,
                'invoice_note' => 'regular',
                'created_at' => now(),
            ],
            [ 
                'branch_id' => 2,
                'user_id' => 6,
                'customer_id' => 9,
                'invoice_date' => Carbon::parse(now())->format('Y-m-d'),
                'payment_type' => 'Cash',
                'invoice_total' => 100.00,
                'invoice_discount' => 0.00,
                'invoice_nettotal' => 100.00,
                'invoice_received' => 100.00,
                'invoice_due' => 0.00,
                'invoice_note' => 'regular',
                'created_at' => now(),
            ],
            [ 
                'branch_id' => 2,
                'user_id' => 6,
                'customer_id' => 8,
                'invoice_date' => Carbon::parse(now())->format('Y-m-d'),
                'payment_type' => 'Cash',
                'invoice_total' => 450.00,
                'invoice_discount' => 20.00,
                'invoice_nettotal' => 430.00,
                'invoice_received' => 400.00,
                'invoice_due' => 30.00,
                'invoice_note' => 'regular',
                'created_at' => now(),
            ],
            [ 
                'branch_id' => 1,
                'user_id' => 5,
                'customer_id' => 2,
                'invoice_date' => Carbon::parse(now())->format('Y-m-d'),
                'payment_type' => 'Cash',
                'invoice_total' => 270.00,
                'invoice_discount' => 20.00,
                'invoice_nettotal' => 250.00,
                'invoice_received' => 250.00,
                'invoice_due' => 0.00,
                'invoice_note' => 'regular',
                'created_at' => now(),
            ],
            [ 
                'branch_id' => 1,
                'user_id' => 5,
                'customer_id' => 3,
                'invoice_date' => Carbon::parse(now())->format('Y-m-d'),
                'payment_type' => 'Cash',
                'invoice_total' => 90.00,
                'invoice_discount' => 0.00,
                'invoice_nettotal' => 90.00,
                'invoice_received' => 80.00,
                'invoice_due' => 10.00,
                'invoice_note' => 'regular',
                'created_at' => now(),
            ],
            [ 
                'branch_id' => 2,
                'user_id' => 6,
                'customer_id' => 6,
                'invoice_date' => Carbon::parse(now())->format('Y-m-d'),
                'payment_type' => 'Cash',
                'invoice_total' => 425.00,
                'invoice_discount' => 0.00,
                'invoice_nettotal' => 425.00,
                'invoice_received' => 425.00,
                'invoice_due' => 0.00,
                'invoice_note' => 'regular',
                'created_at' => now(),
            ],
            [ 
                'branch_id' => 2,
                'user_id' => 6,
                'customer_id' => 7,
                'invoice_date' => Carbon::parse(now())->format('Y-m-d'),
                'payment_type' => 'Cash',
                'invoice_total' => 560.00,
                'invoice_discount' => 10.00,
                'invoice_nettotal' => 550.00,
                'invoice_received' => 500.00,
                'invoice_due' => 50.00,
                'invoice_note' => 'regular',
                'created_at' => now(),
            ],
            [ 
                'branch_id' => 1,
                'user_id' => 5,
                'customer_id' => 4,
                'invoice_date' => Carbon::parse(now())->format('Y-m-d'),
                'payment_type' => 'Cash',
                'invoice_total' => 420.00,
                'invoice_discount' => 0.00,
                'invoice_nettotal' => 420.00,
                'invoice_received' => 400.00,
                'invoice_due' => 20.00,
                'invoice_note' => 'regular',
                'created_at' => now(),
            ],
            [ 
                'branch_id' => 1,
                'user_id' => 5,
                'customer_id' => 5,
                'invoice_date' => Carbon::parse(now())->format('Y-m-d'),
                'payment_type' => 'Cash',
                'invoice_total' => 525.00,
                'invoice_discount' => 0.00,
                'invoice_nettotal' => 525.00,
                'invoice_received' => 525.00,
                'invoice_due' => 0.00,
                'invoice_note' => 'regular',
                'created_at' => now(),
            ],
            [ 
                'branch_id' => 1,
                'user_id' => 5,
                'customer_id' => 1,
                'invoice_date' => Carbon::parse(now())->format('Y-m-d'),
                'payment_type' => 'Cash',
                'invoice_total' => 400.00,
                'invoice_discount' => 0.00,
                'invoice_nettotal' => 400.00,
                'invoice_received' => 400.00,
                'invoice_due' => 0.00,
                'invoice_note' => 'regular',
                'created_at' => now(),
            ],
            [ 
                'branch_id' => 2,
                'user_id' => 6,
                'customer_id' => 1,
                'invoice_date' => Carbon::parse(now())->format('Y-m-d'),
                'payment_type' => 'Cash',
                'invoice_total' => 690.00,
                'invoice_discount' => 0.00,
                'invoice_nettotal' => 690.00,
                'invoice_received' => 690.00,
                'invoice_due' => 0.00,
                'invoice_note' => 'regular',
                'created_at' => now(),
            ],
            [ 
                'branch_id' => 2,
                'user_id' => 6,
                'customer_id' => 1,
                'invoice_date' => Carbon::parse(now())->format('Y-m-d'),
                'payment_type' => 'Cash',
                'invoice_total' => 620.00,
                'invoice_discount' => 0.00,
                'invoice_nettotal' => 620.00,
                'invoice_received' => 620.00,
                'invoice_due' => 0.00,
                'invoice_note' => 'regular',
                'created_at' => now(),
            ],
        ]);
    }
}
