<?php

use App\Purchase;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class PurchasesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        Purchase::insert([
            [ 
                'purchase_invoice_id' => 21314151,
                'purchase_date' => Carbon::parse(now())->format('Y-m-d'),
                'user_id' => 5,
                'branch_id' => 1,
                'supplier_id' => 4,
                'purchase_total' => 13500.00,
                'purchase_discount' => 0.00,
                'purchase_paid' => 13500.00,
                'purchase_nettotal' => 13500.00,
                'purchase_due' => 0.00,
                'payment_type' => 'Cash',
                'purchase_note' => 'regular',
                'created_at' => now(),
            ],
            [ 
                'purchase_invoice_id' => 31314151,
                'purchase_date' => Carbon::parse(now())->format('Y-m-d'),
                'user_id' => 6,
                'branch_id' => 2,
                'supplier_id' => 5,
                'purchase_total' => 20000.00,
                'purchase_discount' => 0.00,
                'purchase_paid' => 20000.00,
                'purchase_nettotal' => 20000.00,
                'purchase_due' => 0.00,
                'payment_type' => 'Cash',
                'purchase_note' => 'regular',
                'created_at' => now(),
            ],
            [ 
                'purchase_invoice_id' => 41314151,
                'purchase_date' => Carbon::parse(now())->format('Y-m-d'),
                'user_id' => 5,
                'branch_id' => 1,
                'supplier_id' => 2,
                'purchase_total' => 33000.00,
                'purchase_discount' => 0.00,
                'purchase_paid' => 30000.00,
                'purchase_nettotal' => 33000.00,
                'purchase_due' => 3000.00,
                'payment_type' => 'Cash',
                'purchase_note' => 'regular',
                'created_at' => now(),
            ],
            [ 
                'purchase_invoice_id' => 32324252,
                'purchase_date' => Carbon::parse(now())->format('Y-m-d'),
                'user_id' => 6,
                'branch_id' => 2,
                'supplier_id' => 3,
                'purchase_total' => 39500.00,
                'purchase_discount' => 0.00,
                'purchase_paid' => 39000.00,
                'purchase_nettotal' => 39500.00,
                'purchase_due' => 500.00,
                'payment_type' => 'Cash',
                'purchase_note' => 'regular',
                'created_at' => now(),
            ],
            [ 
                'purchase_invoice_id' => 33334353,
                'purchase_date' => Carbon::parse(now())->format('Y-m-d'),
                'user_id' => 6,
                'branch_id' => 2,
                'supplier_id' => 1,
                'purchase_total' => 66000.00,
                'purchase_discount' => 0.00,
                'purchase_paid' => 66000.00,
                'purchase_nettotal' => 66000.00,
                'purchase_due' => 0.00,
                'payment_type' => 'Cash',
                'purchase_note' => 'regular',
                'created_at' => now(),
            ],
            [ 
                'purchase_invoice_id' => 22324252,
                'purchase_date' => Carbon::parse(now())->format('Y-m-d'),
                'user_id' => 5,
                'branch_id' => 1,
                'supplier_id' => 6,
                'purchase_total' => 118500.00,
                'purchase_discount' => 0.00,
                'purchase_paid' => 118500.00,
                'purchase_nettotal' => 118500.00,
                'purchase_due' => 0.00,
                'payment_type' => 'Cash',
                'purchase_note' => 'regular',
                'created_at' => now(),
            ],
            [ 
                'purchase_invoice_id' => 42426161,
                'purchase_date' => Carbon::parse(now())->format('Y-m-d'),
                'user_id' => 5,
                'branch_id' => 1,
                'supplier_id' => 2,
                'purchase_total' => 102000.00,
                'purchase_discount' => 0.00,
                'purchase_paid' => 102000.00,
                'purchase_nettotal' => 102000.00,
                'purchase_due' => 0.00,
                'payment_type' => 'Cash',
                'purchase_note' => 'regular',
                'created_at' => now(),
            ],
            [ 
                'purchase_invoice_id' => 43434152,
                'purchase_date' => Carbon::parse(now())->format('Y-m-d'),
                'user_id' => 6,
                'branch_id' => 2,
                'supplier_id' => 5,
                'purchase_total' => 91000.00,
                'purchase_discount' => 0.00,
                'purchase_paid' => 91000.00,
                'purchase_nettotal' => 91000.00,
                'purchase_due' => 0.00,
                'payment_type' => 'Cash',
                'purchase_note' => 'regular',
                'created_at' => now(),
            ],
            [ 
                'purchase_invoice_id' => 50150102,
                'purchase_date' => Carbon::parse(now())->format('Y-m-d'),
                'user_id' => 5,
                'branch_id' => 1,
                'supplier_id' => 4,
                'purchase_total' => 35000.00,
                'purchase_discount' => 0.00,
                'purchase_paid' => 35000.00,
                'purchase_nettotal' => 35000.00,
                'purchase_due' => 0.00,
                'payment_type' => 'Cash',
                'purchase_note' => 'regular',
                'created_at' => now(),
            ],
            [ 
                'purchase_invoice_id' => 60160212,
                'purchase_date' => Carbon::parse(now())->format('Y-m-d'),
                'user_id' => 6,
                'branch_id' => 2,
                'supplier_id' => 5,
                'purchase_total' => 57000.00,
                'purchase_discount' => 0.00,
                'purchase_paid' => 57000.00,
                'purchase_nettotal' => 57000.00,
                'purchase_due' => 0.00,
                'payment_type' => 'Cash',
                'purchase_note' => 'regular',
                'created_at' => now(),
            ],
        ]);
    }
}
