<?php

use Carbon\Carbon;
use App\PurchaseDetails;
use Illuminate\Database\Seeder;

class PurchaseDetailsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        PurchaseDetails::insert([
            [
                'purchase_id' => 1,
                'medicine_id' => 10,
                'medicine_name' => 'Trevox 500',
                'darr_no' => '321-50-60',
                'sell_price' => 15.00,
                'medicine_price' => 12.00,
                'stock' => 995,  // 1000
                'stock_original' => 1000,
                'total_price' => 12000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2056-12-05'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 1,
                'medicine_id' => 7,
                'medicine_name' => 'Napa 500',
                'darr_no' => '186-30-06',
                'sell_price' => 2.00,
                'medicine_price' => 1.50,
                'stock' => 950, // 1000
                'stock_original' => 1000,
                'total_price' => 1500.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2056-12-06'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 2,
                'medicine_id' => 11,
                'medicine_name' => 'Pol Plus BP 500mg',
                'darr_no' => '083-255-006',
                'sell_price' => 3.00,
                'medicine_price' => 2.00,
                'stock' => 1980, // 2000
                'stock_original' => 2000,
                'total_price' => 4000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2054-11-07'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 2,
                'medicine_id' => 6,
                'medicine_name' => 'Doxicap 100',
                'darr_no' => '002-17-60',
                'sell_price' => 10.00,
                'medicine_price' => 8.00,
                'stock' => 1950, // 2000
                'stock_original' => 2000,
                'total_price' => 16000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2054-09-08'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 3,
                'medicine_id' => 2,
                'medicine_name' => 'Duofix 500',
                'darr_no' => '259-142-064',
                'sell_price' => 15.00,
                'medicine_price' => 12.50,
                'stock' => 1965, // 2000
                'stock_original' => 2000,
                'total_price' => 25000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2052-09-09'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 3,
                'medicine_id' => 1,
                'medicine_name' => 'Fenadin 180',
                'darr_no' => '353-51-021',
                'sell_price' => 10.00,
                'medicine_price' => 8.00,
                'stock' => 968, // 1000
                'stock_original' => 1000,
                'total_price' => 8000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2052-09-02'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 4,
                'medicine_id' => 3,
                'medicine_name' => 'Rhinozol 15ml',
                'darr_no' => '036-120-74',
                'sell_price' => 25.00,
                'medicine_price' => 22.00,
                'stock' => 495, // 500
                'stock_original' => 500,
                'total_price' => 11000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2052-03-09'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 4,
                'medicine_id' => 2,
                'medicine_name' => 'Duofix 500',
                'darr_no' => '300-152-074',
                'sell_price' => 15.00,
                'medicine_price' => 12.50,
                'stock' => 960, // 1000
                'stock_original' => 1000,
                'total_price' => 12500.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2052-04-09'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 4,
                'medicine_id' => 1,
                'medicine_name' => 'Fenadin 180',
                'darr_no' => '455-52-031',
                'sell_price' => 10.00,
                'medicine_price' => 8.00,
                'stock' => 1960, // 2000
                'stock_original' => 2000,
                'total_price' => 16000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2050-05-09'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 5,
                'medicine_id' => 9,
                'medicine_name' => 'Montair 10mg',
                'darr_no' => '122-22-444',
                'sell_price' => 20.00,
                'medicine_price' => 18.00,
                'stock' => 3000,
                'stock_original' => 3000,
                'total_price' => 54000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2050-12-31'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 5,
                'medicine_id' => 8,
                'medicine_name' => 'Sitagil M 50/1000ER',
                'darr_no' => '116-973-43',
                'sell_price' => 10.00,
                'medicine_price' => 8.00,
                'stock' => 1500,
                'stock_original' => 1500,
                'total_price' => 12000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2050-12-01'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 6,
                'medicine_id' => 5,
                'medicine_name' => 'Zif-CI',
                'darr_no' => '321-67-045',
                'sell_price' => 12.00,
                'medicine_price' => 10.00,
                'stock' => 1975, // 2000
                'stock_original' => 2000,
                'total_price' => 20000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2048-12-31'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 6,
                'medicine_id' => 4,
                'medicine_name' => 'Ranid 150mg',
                'darr_no' => '242-22-005',
                'sell_price' => 5.00,
                'medicine_price' => 3.50,
                'stock' => 2970, // 3000
                'stock_original' => 3000,
                'total_price' => 10500.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2048-10-31'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 6,
                'medicine_id' => 3,
                'medicine_name' => 'Rhinozol 15ml',
                'darr_no' => '037-130-84',
                'sell_price' => 25.00,
                'medicine_price' => 22.00,
                'stock' => 3992, // 4000
                'stock_original' => 4000,
                'total_price' => 88000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2048-05-01'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 7,
                'medicine_id' => 6,
                'medicine_name' => 'Doxicap 100',
                'darr_no' => '443-443-244',
                'sell_price' => 10.00,
                'medicine_price' => 8.00,
                'stock' => 3000,
                'stock_original' => 3000,
                'total_price' => 24000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2046-12-10'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 7,
                'medicine_id' => 8,
                'medicine_name' => 'Sitagil M 50/1000ER',
                'darr_no' => '611-873-53',
                'sell_price' => 10.00,
                'medicine_price' => 8.00,
                'stock' => 2000,
                'stock_original' => 2000,
                'total_price' => 16000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2046-12-01'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 7,
                'medicine_id' => 9,
                'medicine_name' => 'Montair 10mg',
                'darr_no' => '009-111-616',
                'sell_price' => 20.00,
                'medicine_price' => 18.00,
                'stock' => 3000,
                'stock_original' => 3000,
                'total_price' => 54000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2046-12-31'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 7,
                'medicine_id' => 11,
                'medicine_name' => 'Pol Plus BP 500mg',
                'darr_no' => '009-111-616',
                'sell_price' => 3.00,
                'medicine_price' => 2.00,
                'stock' => 4000,
                'stock_original' => 4000,
                'total_price' => 8000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2044-10-30'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 8,
                'medicine_id' => 4,
                'medicine_name' => 'Ranid 150mg',
                'darr_no' => '990-991-992',
                'sell_price' => 5.00,
                'medicine_price' => 3.50,
                'stock' => 2000,
                'stock_original' => 2000,
                'total_price' => 7000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2044-12-31'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 8,
                'medicine_id' => 5,
                'medicine_name' => 'Zif-CI',
                'darr_no' => '880-881-992',
                'sell_price' => 12.00,
                'medicine_price' => 10.00,
                'stock' => 2960, // 3000
                'stock_original' => 3000,
                'total_price' => 30000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2042-11-30'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 8,
                'medicine_id' => 7,
                'medicine_name' => 'Napa 500',
                'darr_no' => '770-771-772',
                'sell_price' => 2.00,
                'medicine_price' => 1.50,
                'stock' => 3965, // 4000
                'stock_original' => 4000,
                'total_price' => 6000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2042-10-30'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 8,
                'medicine_id' => 10,
                'medicine_name' => 'Trevox 500',
                'darr_no' => '660-661-662',
                'sell_price' => 15.00,
                'medicine_price' => 12.00,
                'stock' => 3965, // 4000
                'stock_original' => 4000,
                'total_price' => 48000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2040-12-31'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 9,
                'medicine_id' => 7,
                'medicine_name' => 'Napa 500',
                'darr_no' => '660-661-662',
                'sell_price' => 2.00,
                'medicine_price' => 1.50,
                'stock' => 2000, // 4000
                'stock_original' => 2000,
                'total_price' => 3000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2042-12-31'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 9,
                'medicine_id' => 4,
                'medicine_name' => 'Ranid 150mg',
                'darr_no' => '243-23-006',
                'sell_price' => 5.00,
                'medicine_price' => 3.50,
                'stock' => 2000, // 4000
                'stock_original' => 2000,
                'total_price' => 7000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2042-12-31'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 9,
                'medicine_id' => 2,
                'medicine_name' => 'Duofix 500',
                'darr_no' => '260-143-065',
                'sell_price' => 15.00,
                'medicine_price' => 12.50,
                'stock' => 2005, 
                'stock_original' => 2000,
                'total_price' => 25000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2042-12-31'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 10,
                'medicine_id' => 6,
                'medicine_name' => 'Doxicap 100',
                'darr_no' => '003-123-009',
                'sell_price' => 10.00,
                'medicine_price' => 8.00,
                'stock' => 2005, 
                'stock_original' => 2000,
                'total_price' => 16000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2050-12-31'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 10,
                'medicine_id' => 1,
                'medicine_name' => 'Fenadin 180',
                'darr_no' => '004-321-008',
                'sell_price' => 10.00,
                'medicine_price' => 8.00,
                'stock' => 2005, 
                'stock_original' => 2000,
                'total_price' => 16000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2050-12-31'),
                'created_at' => now(),
            ],
            [
                'purchase_id' => 10,
                'medicine_id' => 2,
                'medicine_name' => 'Duofix 500',
                'darr_no' => '500-321-006',
                'sell_price' => 15.00,
                'medicine_price' => 12.50,
                'stock' => 2005, 
                'stock_original' => 2000,
                'total_price' => 25000.00,
                'expiry_date' => Carbon::createFromFormat('Y-m-d', '2050-12-31'),
                'created_at' => now(),
            ],
        ]);
    }
}
