<?php

use App\User;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        Schema::disableForeignKeyConstraints();
        User::truncate();

        User::insert([
            [
                'name' => 'Meela Khan',
                'phone' => '017777777777',
                'username' => 'meela',
                'email' => 'meela@voila.com',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role_id' => 1,
                'nid' => '1990123456789001',
                'remember_token' => Str::random(10),
                'photo' => '',
                'current_address' => "Dhanmondi",
                'permanent_address' => "Pabna",
                'note' => "Good!",
                'status' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'Leela Khan',
                'phone' => '018888888888',
                'username' => 'leela',
                'email' => 'leela@voila.com',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role_id' => 2,
                'nid' => '1990123456789002',
                'remember_token' => Str::random(10),
                'photo' => '',
                'current_address' => "Gulshan",
                'permanent_address' => "Sylhet",
                'note' => "Good!",
                'status' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'Sheela Khan',
                'phone' => '0155555555555',
                'username' => 'sheela',
                'email' => 'sheela@voila.com',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role_id' => 2,
                'nid' => '1990123456789003',
                'remember_token' => Str::random(10),
                'photo' => '',
                'current_address' => "Uttara",
                'permanent_address' => "Chittagong",
                'note' => "Good!",
                'status' => 1,
                'created_at' => now(),
            ],
            [
                'name' => 'Weela Khan',
                'phone' => '01666666666',
                'username' => 'weela',
                'email' => 'weela@voila.com',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role_id' => 2,
                'nid' => '1990123456789004',
                'remember_token' => Str::random(10),
                'photo' => '',
                'current_address' => "Jatrabari",
                'permanent_address' => "Rajshahi",
                'note' => "Good!",
                'status' => 1,
                'created_at' => now(),
            ],

            [
                'name' => 'Musa Khan',
                'phone' => '019999999999',
                'username' => 'musa',
                'email' => 'musa@voila.com',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role_id' => 3,
                'nid' => '1990123456789005',
                'remember_token' => Str::random(10),
                'photo' => '',
                'current_address' => "Mirpur 11",
                'permanent_address' => "Netrokona",
                'note' => "Good!",
                'status' => 1,
                'created_at' => now(),
            ],

            [
                'name' => 'Rusa Khan',
                'phone' => '019999999911',
                'username' => 'rusa',
                'email' => 'rusa@voila.com',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role_id' => 3,
                'nid' => '1990123456789006',
                'remember_token' => Str::random(10),
                'photo' => '',
                'current_address' => "Mirpur 12",
                'permanent_address' => "Rangpur",
                'note' => "Good!",
                'status' => 1,
                'created_at' => now(),
            ],

            // [
            //     'name' => 'Staffone Khan',
            //     'phone' => '0144444444411',
            //     'username' => 'staffone',
            //     'email' => 'staffone@voila.com',
            //     'email_verified_at' => now(),
            //     'password' => bcrypt('12345678'),
            //     'role_id' => 5,
            //     'national_id' => '1990123456789007',
            //     'remember_token' => Str::random(10),
            //     'photo' => '',
            //     'current_address' => "Mirpur 10",
            //     'permanent_address' => "Khulna",
            //     'note' => "Good!",
            //     'status' => 1,
            //     'created_at' => now(),
            // ],
            // [
            //     'name' => 'Stafftwo Khan',
            //     'phone' => '0144444444412',
            //     'username' => 'stafftwo',
            //     'email' => 'stafftwo@voila.com',
            //     'email_verified_at' => now(),
            //     'password' => bcrypt('12345678'),
            //     'role_id' => 5,
            //     'national_id' => '1990123456789008',
            //     'remember_token' => Str::random(10),
            //     'photo' => '',
            //     'current_address' => "Mirpur 10",
            //     'permanent_address' => "Pabna",
            //     'note' => "Good!",
            //     'status' => 1,
            //     'created_at' => now(),
            // ],
            // [
            //     'name' => 'Staffthree Khan',
            //     'phone' => '0144444444413',
            //     'username' => 'staffthree',
            //     'email' => 'staffthree@voila.com',
            //     'email_verified_at' => now(),
            //     'password' => bcrypt('12345678'),
            //     'role_id' => 5,
            //     'national_id' => '1990123456789009',
            //     'remember_token' => Str::random(10),
            //     'photo' => '',
            //     'current_address' => "Mirpur 11",
            //     'permanent_address' => "Jessore",
            //     'note' => "Good!",
            //     'status' => 1,
            //     'created_at' => now(),
            // ],
            // [
            //     'name' => 'Stafffour Khan',
            //     'phone' => '0144444444414',
            //     'username' => 'stafffour',
            //     'email' => 'stafffour@voila.com',
            //     'email_verified_at' => now(),
            //     'password' => bcrypt('12345678'),
            //     'role_id' => 5,
            //     'national_id' => '19901234567890010',
            //     'remember_token' => Str::random(10),
            //     'photo' => '',
            //     'current_address' => "Mirpur 11",
            //     'permanent_address' => "Bogura",
            //     'note' => "Good!",
            //     'status' => 1,
            //     'created_at' => now(),
            // ],
            // [
            //     'name' => 'Stafffive Khan',
            //     'phone' => '0144444444415',
            //     'username' => 'stafffive',
            //     'email' => 'stafffive@voila.com',
            //     'email_verified_at' => now(),
            //     'password' => bcrypt('12345678'),
            //     'role_id' => 5,
            //     'national_id' => '19901234567890011',
            //     'remember_token' => Str::random(10),
            //     'photo' => '',
            //     'current_address' => "Mirpur 12",
            //     'permanent_address' => "Chattogram",
            //     'note' => "Good!",
            //     'status' => 1,
            //     'created_at' => now(),
            // ],
            // [
            //     'name' => 'Staffsix Khan',
            //     'phone' => '0144444444415',
            //     'username' => 'staffsix',
            //     'email' => 'staffsix@voila.com',
            //     'email_verified_at' => now(),
            //     'password' => bcrypt('12345678'),
            //     'role_id' => 5,
            //     'national_id' => '19901234567890012',
            //     'remember_token' => Str::random(10),
            //     'photo' => '',
            //     'current_address' => "Mirpur 12",
            //     'permanent_address' => "Dhaka",
            //     'note' => "Good!",
            //     'status' => 1,
            //     'created_at' => now(),
            // ],
        ]);

        Schema::enableForeignKeyConstraints();
    }
}
